import { fetchProviderJson, findModel, noKnownUsdEstimate } from "./shared.mjs";

const API = "https://api.klingai.com/v1/videos/image2video";

export const KLING_MODELS = Object.freeze([
  {
    id: "kling-v3",
    label: "Kling Video 3.0",
    durations: [5, 10],
    resolutions: ["720p", "1080p"],
    capabilities: { prompt: true, startFrame: true, endFrame: true, referenceVideo: false, cameraControl: false, audio: true },
  },
]);

const authHeaders = (token) => ({ Authorization: `Bearer ${token}`, "Content-Type": "application/json" });
const modelOf = (id) => findModel(KLING_MODELS, id, "Kling");

export function validateKlingSpec(spec) {
  const model = modelOf(spec.model);
  const errors = [];
  const warnings = [];
  if (!spec.prompt?.trim()) errors.push("prompt is required");
  if (!model.durations.includes(spec.durationSeconds)) errors.push(`${model.label} duration must be 5 or 10 seconds`);
  if (!model.resolutions.includes(spec.resolution)) errors.push(`${model.label} resolution must be 720p or 1080p`);
  if (!spec.conditioning?.startFrame) errors.push(`${model.label} requires a staged start frame`);
  if (spec.conditioning?.referenceVideo) warnings.push("Kling reference-video request mapping is unverified and will not be sent");
  if (spec.camera) warnings.push("Kling 3.0 camera-control payload is unverified; staged frames and composed prompt will carry the authored camera move");
  return { ok: errors.length === 0, errors, warnings, model };
}

export function mapKlingRequest(spec) {
  const verdict = validateKlingSpec(spec);
  if (!verdict.ok) throw new Error(verdict.errors[0]);
  const body = {
    model_name: verdict.model.id,
    image: spec.conditioning.startFrame,
    prompt: spec.prompt,
    mode: spec.resolution === "1080p" ? "pro" : "std",
    duration: String(spec.durationSeconds),
    sound: "on",
  };
  if (spec.conditioning.endFrame) body.image_tail = spec.conditioning.endFrame;
  return body;
}

export async function submitKling(spec, { token = process.env.KLING_API_TOKEN, fetchImpl = fetch, signal, ...retryOptions } = {}) {
  if (!token) throw new Error("KLING_API_TOKEN is not configured; provide a server-side token generated by Kling's documented authentication flow");
  const verdict = validateKlingSpec(spec);
  if (!verdict.ok) throw new Error(verdict.errors[0]);
  const { response, payload } = await fetchProviderJson(API, { method: "POST", headers: authHeaders(token), body: JSON.stringify(mapKlingRequest(spec)) }, { fetchImpl, signal, ...retryOptions });
  if (!response.ok) throw new Error(`Kling submit failed (HTTP ${response.status})`);
  const providerJobId = payload.data?.task_id;
  if (!providerJobId) throw new Error("Kling submit response has no task id");
  return { providerJobId, warnings: verdict.warnings };
}

export async function pollKling(providerJobId, { token = process.env.KLING_API_TOKEN, fetchImpl = fetch, signal, ...retryOptions } = {}) {
  if (!token) throw new Error("KLING_API_TOKEN is not configured");
  const { response, payload } = await fetchProviderJson(`${API}/${encodeURIComponent(providerJobId)}`, { headers: authHeaders(token) }, { fetchImpl, signal, ...retryOptions });
  if (!response.ok) throw new Error(`Kling poll failed (HTTP ${response.status})`);
  const remote = String(payload.data?.task_status || "").toLowerCase();
  const status = remote === "succeed" || remote === "succeeded" ? "succeeded" : ["failed", "canceled", "cancelled"].includes(remote) ? "failed" : "processing";
  return { status, progress: null, outputUrl: status === "succeeded" ? payload.data?.task_result?.videos?.[0]?.url ?? null : null, failure: status === "failed" ? payload.data?.task_status_msg || payload.message || "generation failed" : null, raw: payload };
}

export const klingProvider = Object.freeze({
  id: "kling",
  label: "Kling AI",
  auth: { type: "bearer-env", env: "KLING_API_TOKEN" },
  available: () => Boolean(process.env.KLING_API_TOKEN),
  models: KLING_MODELS,
  validate: validateKlingSpec,
  estimateCost: noKnownUsdEstimate,
  submit: submitKling,
  poll: pollKling,
});
