#!/usr/bin/env node
import { writeFileSync } from "node:fs";
globalThis.port = Number(process.env.CDP_PORT || 9222);
globalThis.targets = await (await fetch(`http://127.0.0.1:${port}/json`)).json();
globalThis.page = targets.find((t) => t.type === "page" && t.webSocketDebuggerUrl);
globalThis.ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
globalThis.nextId = 1; const pending = new Map();
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (!m.id || !pending.has(m.id)) return; const { resolve } = pending.get(m.id); pending.delete(m.id); resolve(m.result); };
globalThis.send = (method, params = {}) => new Promise((resolve) => { const id = nextId++; pending.set(id, { resolve }); ws.send(JSON.stringify({ id, method, params })); });
globalThis.evaluate = async (expression) => { const r = await send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true }); return r.result?.value; };
await send("Runtime.enable"); await send("Page.enable");
await new Promise((r) => setTimeout(r, 3500));
for (let i = 0; i < 50 && !(await evaluate("!!window.__sceneHistory && document.querySelectorAll('.hierarchy-row').length > 0").catch(() => false)); i++) await new Promise((r) => setTimeout(r, 200));
await evaluate("document.querySelector('.add-object-trigger').click()");
await new Promise((r) => setTimeout(r, 400));
await evaluate("[...document.querySelectorAll('.add-object-item')].find(b => b.textContent.startsWith('Cube')).click()");
await new Promise((r) => setTimeout(r, 1500));
globalThis.shot = await send("Page.captureScreenshot", { format: "png", clip: { x: 1220, y: 45, width: 380, height: 420, scale: 2 } });
writeFileSync(new URL("../artifacts/insp-zoom.png", import.meta.url), Buffer.from(shot.data, "base64"));
console.log("saved");
ws.close();
